---
galaxy_info:
  role_name: security_wazuh
  author: localnet
  description: Deploy Wazuh SIEM/XDR stack (upstream wazuh-manager/indexer/dashboard images)
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Windows
      versions:
        - "all"

dependencies: []
