serverAddr = "PROXY_FRPS_IP"
serverPort = 7000
auth.additionalScopes = ["HeartBeats", "NetworkConns"]
auth.method = "token"
auth.token = "${PROXY_FRP_AUTH_TOKEN}"

[[proxies]]
name = "http"
type = "tcp"
localIP = "127.0.0.1"
localPort = 80
remotePort = 80
transport.useEncryption = true
transport.proxyProtocolVersion = "v2"

[[proxies]]
name = "https"
type = "tcp"
localIP = "127.0.0.1"
localPort = 443
remotePort = 443
transport.useEncryption = true
transport.proxyProtocolVersion = "v2"
