jwt_secret: ${PROXY_AUTH_JWT_SECRET} # openssl rand -base64 32

log:
  level: debug

totp:
  issuer: ${LOCALNET_HOSTNAME}

authentication_backend:
  file:
    path: /etc/authelia/authelia-users-database.yml

access_control:
  rules:
    - domain: ${APP_FILES_HOSTNAME}
      resources:
        - '^/share([/?].*)?$'
        - '^/static([/?].*)?$'
        - '^/api/public([/?].*)?$'
      policy: bypass
    - domain: ${PROXY_AUTH_HOSTNAME}
      policy: bypass
    - domain: '*.${LOCALNET_HOSTNAME}'
      policy: two_factor

session:
  secret: ${PROXY_AUTH_SESSION_SECRET} # openssl rand -base64 32
  cookies:
    - domain: ${LOCALNET_HOSTNAME}
      authelia_url: https://${PROXY_AUTH_HOSTNAME}
  redis:
    host: authelia-db
    port: 6379

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  encryption_key: ${PROXY_AUTH_ENCRYPTION_KEY} # openssl rand -base64 32
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt

identity_providers:
  ## See: https://www.authelia.com/c/oidc
  oidc:
    # openssl rand -base64 32
    enable_client_debug_messages: false
    clients:
      - client_id: 'open-webui'
        client_name: 'Open WebUI'
        ## `docker run authelia/authelia:latest authelia crypto has generate pbkdf2 --bariant sha512 --random --random.length 72 --random.charset rfc3986`
        client_secret:
        public: false
        authorization_policy: 'two_factor'
        require_pkce: false
        pkce_challenge_method: ''
        redirect_uris:
          - 'http://${AI_SERVICES_OPEN_WEBUI_HOST_NAME}:${AI_SERVICES_OPEN_WEBUI_CONTAINER_PORT}/oauth/oidc/callback'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
          - 'groups'
        response_types:
          - 'code'
        grant_types:
          - 'authorization_code'
        access_token_signed_response_alg: 'none'
        userinfo_signed_response_alg: 'none'
        token_endpoint_auth_method: 'client_secret_basic'
      - client_id: 'visual-gallery'
        client_name: 'Immich Visual Gallery'
        ## `docker run authelia/authelia:latest authelia crypto has generate pbkdf2 --bariant sha512 --random --random.length 72 --random.charset rfc3986`
        client_secret:
        public: false
        authorization_policy: 'two_factor'
        require_pkce: false
        pkce_challenge_method: ''
        redirect_uris:
          - 'http://${VISUAL_GALLERY_HOST_NAME}:${VISUAL_GALLERY_HOST_PORT}/auth/login'
          - 'http://${VISUAL_GALLERY_HOST_NAME}:${VISUAL_GALLERY_HOST_PORT}/user-settings'
          - 'app.immich:/'
          - 'app.immich:///oauth-callback'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
        userinfo_signed_response_alg: 'none'
        token_endpoint_auth_method: 'client_secret_post'
        response_types:
          - 'code'
        grant_types:
          - 'authorization_code'
        access_token_signed_response_alg: 'none'

    hmac_secret: '5VuSDlV/rwwmY5ySy16t4bZr9c+0FWwwSfcyFRkY/RQ='
    jwks: # openssl genrsa 2048
      - key: |
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCm/ys6EtzuHNLe
BH2sAj1i0yOXTb2MPRxIB4/47hi5LzYRUkARsjDX15TaFswYLwDZB090ZQxSh/KK
UPE3hS0t93pUtu9qwlSBMjAUdkKgqUBGSUDnRgMYdOFioqK3dhmcVnvd7aq31os3
3xFBrcqFNr6Ca/MYXKFzDA8Ituo9gEZ/0jamSsUYNyc7RVpiDCkp3N61q05V5anD
0vpEOMNQNFRuf/QmZAoEWBwmAFYX1zfF/iMChItnFZwe12i5faEaaNgRnvsw8qoJ
YsuWXuug+VO2LKiDweWhaHYUhkCV15W5UnJlAQAlXmBrvVED2wPaT3zbR2lRWhIE
9jSMTRchAgMBAAECggEAALK6HThrozvYvlTO+s/tEjjwpBB/52qBFsJxE8nHLvwv
nv8zmweN0FOKsMqOVR3Onta4cHolmNzE5xBjbXIgYrow/JU/qeqEpTeguK7wi9if
dh32/VaNHH7pg5MQqXpzVjK0lQw36LgMDMKDVU8l8c6xZKRPoqE0SfSSFWjabiD4
5ZjY4ybeC/cxAiaayU3NrvTN6TQXCdGJc2s3BH5ldl3FWdlqQaK1xM5q9zlW4PU1
LW3/nUBDb19M+c8KLwpW9SSD7z4DMAPjjQiL+z37W8nnxkt+ki05mfvofmsmu12X
tExEzOMMrXIFuzMD4x28mS52a71DQjr4Fkbl5rqFiwKBgQDgeFAZRWF8lrlC34tt
NayyKmLoORV8fJjEAf8BOITg8fWiomJ1HDDBwukUt/H40BuxZvr3FDq6R8Rf8omL
F57wIsWyI1XY1HilHUZXZNK7PO+JEHxsZbFWzmN3Z5X2Y3WhxnL4pwjDt/kz8rCl
+a2GJCBnId7MHELbjAiWZ6fbfwKBgQC+dC8OwFH7I/vfwKRsFQ8Kc6OeVT0XdTuY
k8LgFgs7SgqMluiUsVKH8HEqnCZu2Xmka7Bc9PtPxrO7kk0ggmfc9V6aPokKSECY
+5qVAeZfG8g6qN/ctZGxb5Dsm+UJHE+LHtwiiwzv9feH3d3W9LjJsqfBrfXot2rT
+yfnbnrdXwKBgQCmF8BFAraAxtIsblavp3CyoHRxGpQQee1b05JJ5/VCsSatgXRS
7VoSdVOcNgPAtNRY7zcyDfDql2HyEPe/SOodC8224ziJaaYfnsrGrd7UFuGzTNSU
LKcM8UheOPKYzr1iyAGYhZgRohauXpxhI59HS4ICbeh6pUq/Qx2zlN16pwKBgD3a
9DGhSr77N+G66mvkBweI+ToCSx4kSB/M1bz7y9gMuxJgLNemI7zc3ZRONLlJzpUV
GKmIM1r8mQExifUmBV+hHYGRD+cUAk7tYI5GmLCJEGXk1RgUrGXpazM9ioyD8l2n
vy1E5gXFaAhriZI31xBDAvMHcdeMQpjoeFRU8HiXAoGBAMdS21RQJ4KSZQyXA4nc
fWkzcOrYjHc7HlxwvLjqVUSxEPB4BXZAvI4jeh5JJL6Dh0w4Hu2rB+D6/R2VyiTG
/ETbXMeOvnHwqF4ljkOXmjQCl0r2vMjG83YqAA7egwAFej61e5WlbulPRV//Nbuk
ZrE+/FupY0QyZ9pBGkUHnIoq
-----END PRIVATE KEY-----
