---
galaxy_info:
  role_name: monitoring_uptime_kuma
  author: localnet
  description: Uptime Kuma internal uptime monitoring
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions:
        - bookworm
    - name: Ubuntu
      versions:
        - jammy
        - noble
  galaxy_tags:
    - monitoring
    - uptime
    - docker

dependencies: []
