# Changes applied to this service
_commit: 8ae9a492
_src_path: boilerplate/apps/infrastructure/docker/docker-linux

# Service Identity
_service_name: Lidarr
_service_description: Music collection manager for Usenet and BitTorrent users
_service_name_slug: lidarr
_domain: localnet

# Container & Network
_service_port: 8686
_service_health_endpoint: /health
_use_traefik: true
_enable_monitoring: true

# Features
_include_ui: false
_ui_port: 8686

# Nix Configuration
_nix_system: x86_64-linux
