# Changes applied to this service
_commit: manual_fix
_src_path: manual_fix

# Service Identity
_service_name: Enclosed
_service_description: Minimalistic web app designed for sending private and secure notes
_service_name_slug: enclosed
_domain: localnet

# Container & Network
_service_port: 8787
_service_health_endpoint: /
_use_traefik: true
_enable_monitoring: true

# Features
_include_ui: true
_ui_port: 8787

# Nix Configuration
# _nix_system: x86_64-linux # Disabled, using upstream image
