---
- name: restart libvirtd
  ansible.builtin.systemd:
    name: libvirtd
    state: restarted
  become: true

- name: restart libvirtd (RedHat)
  ansible.builtin.systemd:
    name: libvirtd
    state: restarted
  become: true
