---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: debian:bookworm-slim
    pre_build_image: true
    privileged: true
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /tmp
provisioner:
  name: ansible
verifier:
  name: ansible
