---
- name: Converge
  hosts: all
  become: true
  vars:
    nix_installation_container_mode: true
    nix_installation_skip_installation: true
  tasks:
    - name: Update apt cache and install curl
      ansible.builtin.apt:
        update_cache: true
        name: curl
        state: present
    - name: Include nix-installation role
      ansible.builtin.include_role:
        name: nix-installation
