---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - curl
          - python3-pip
        state: present

    - name: Install python-docker
      ansible.builtin.pip:
        name: docker
        state: present
