---
- name: Verify
  hosts: all
  become: true
  tasks:
    - name: Check Nix is installed
      ansible.builtin.command:
        cmd: nix --version
      register: nix_check
      changed_when: false
      failed_when: nix_check.rc != 0

    - name: Check Nix flakes are available
      ansible.builtin.command:
        cmd: nix flake --help
      register: flake_check
      changed_when: false
      failed_when: flake_check.rc != 0
