---
include:
  - ../../../docker-compose.include.yml

services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard-home
    restart: unless-stopped
    volumes:
      - dns-adguard-conf:/opt/adguardhome/conf
      - dns-adguard-work:/opt/adguardhome/work
    ports:
      - "5354:5354/tcp"
      - "5354:5354/udp"
      - "3000:3000/tcp"
    environment:
      - TZ=UTC
    networks:
      - localnet
