---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: Update apt cache and install curl
      ansible.builtin.apt:
        update_cache: true
        name: curl
        state: present
    - name: Include docker-engine role
      ansible.builtin.include_role:
        name: docker-engine
