---
## This is the file intended to be incldued by ALL other compose files, It includes references to the volumes from docker-compose.shared.yml
## Networks are defined in docker-compose.shared.yml and referenced here as external

## If you're having a problem with networks or volumes not existing, did you run `make up`?

volumes:
  # Base volumes
  nix-config:
    name: localnet-base-nix-config-volume
    external: true
  nix-store:
    name: localnet-base-nix-store-volume
    external: true

  # DNS Services
  dns-adguard-conf:
    name: localnet-dns-adguard-conf
    external: true

  dns-adguard-work:
    name: localnet-dns-adguard-work
    external: true

  dns-cache:
    name: localnet-dns-cache-volume
    external: true

  dns-blocklist-archive:
    name: localnet-dns-blocklist-archive-volume
    external: true

  dns-blocklist-cdbs:
    name: localnet-dns-blocklist-cdbs-volume
    external: true

  dns-coredns-cache:
    name: localnet-dns-coredns-cache-volume
    external: true

  # NTP Services
  chronyd-data:
    name: localnet-ntp-cache-volume
    external: true

  # Web Proxy Services
  web-cache:
    name: localnet-web-cache-volume
    external: true

  # WireGuard
  wireguard-direct-config:
    name: localnet-wireguard-direct-config-volume
    external: true

  wireguard-transparent-config:
    name: localnet-wireguard-transparent-config-volume
    external: true

  # LocalStack
  localstack-data:
    name: localnet-localstack-data-volume
    external: true

  # Security
  ## Dockerproxy
  dockerproxy-ro:
    name: localnet-dockerproxy-ro-volume
    external: true
  dockerproxy-rw:
    name: localnet-dockerproxy-rw-volume
    external: true

  authelia-db:
    name: localnet-security-authelia-db-volume
    external: true
  wud-store:
    name: localnet-security-wud-store-volume
    external: true
  tugtainer_data:
    name: localnet-security-tugtainer-data-volume
    external: true
  crowdsec-data:
    name: localnet-security-crowdsec-data-volume
    external: true
  crowdsec-config:
    name: localnet-security-crowdsec-config-volume
    external: true
  crowdsec-db:
    name: localnet-security-crowdsec-db-volume
    external: true
  traefik-access-logs:
    name: localnet-security-traefik-accesslog-volume
    external: true

  # Artifact repository services (Nexus & Verdaccio)
  nexus-data:
    name: localnet-nexus-data-volume
    external: true
  verdaccio-data:
    name: localnet-verdaccio-data-volume
    external: true
  attic-data:
    name: localnet-attic-data-volume
    external: true
  nix-snapshotter-data:
    name: localnet-nix-snapshotter-data-volume
    external: true
  harmonia-data:
    name: localnet-harmonia-data-volume
    external: true
  ncps-data:
    name: localnet-ncps-data-volume
    external: true
  # Shared persistent volumes
  asdf-cache:
    name: localnet-artifact-asdf-cache-volume
    external: true
  bazel-cache:
    name: localnet-artifact-bazel-cache-volume
    external: true
  conda-cache:
    name: localnet-artifact-conda-cache-volume
    external: true
  dart-cache:
    name: localnet-artifact-dart-cache-volume
    external: true
  dotnet-cache:
    name: localnet-artifact-dotnet-cache-volume
    external: true
  elixir-cache:
    name: localnet-artifact-elixir-cache-volume
    external: true
  go-cache:
    name: localnet-artifact-go-cache-volume
    external: true
  gradle-cache:
    name: localnet-artifact-gradle-cache-volume
    external: true
  haskell-cabal-cache:
    name: localnet-artifact-haskell-cabal-cache-volume
    external: true
  haskell-stack-cache:
    name: localnet-artifact-haskell-stack-cache-volume
    external: true
  java-m2-cache:
    name: localnet-artifact-java-m2-cache-volume
    external: true
  mise-cache:
    name: localnet-artifact-mise-cache-volume
    external: true
  nvm-cache:
    name: localnet-artifact-nvm-cache-volume
    external: true
  php-cache:
    name: localnet-artifact-php-cache-volume
    external: true
  poetry-cache:
    name: localnet-artifact-poetry-cache-volume
    external: true
  pnpm-store:
    name: localnet-artifact-pnpm-store-volume
    external: true
  pyenv-cache:
    name: localnet-artifact-pyenv-cache-volume
    external: true
  python-cache:
    name: localnet-artifact-python-cache-volume
    external: true
  ruby-cache:
    name: localnet-artifact-ruby-cache-volume
    external: true
  rust-cargo-cache:
    name: localnet-artifact-rust-cargo-cache-volume
    external: true
  rust-rustup-cache:
    name: localnet-artifact-rust-rustup-cache-volume
    external: true
  sdkman-cache:
    name: localnet-artifact-sdkman-cache-volume
    external: true
  turbo-cache:
    name: localnet-artifact-turbo-cache-volume
    external: true
  unity-cache:
    name: localnet-artifact-unity-cache-volume
    external: true
  vscode-cache:
    name: localnet-artifact-vscode-cache-volume
    external: true

networks:
  localnet:
    name: localnet-network
    external: true

  wireguard:
    name: wireguard-network
    external: true

  codeassist:
    name: codeassist-network
    external: true

  null-network:
    name: null-network
    external: true
