---
# Gluetun

- name: Deploy gluetun container
  community.docker.docker_container:
    name: localnet-vpn-gluetun
    image: qmcgaw/gluetun
    state: started
    restart_policy: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - name: "{{ localnet_network_name }}"
    volumes:
      - "{{ localnet_services_dir }}/vpn/gluetun/mounts/etc/gluetun:/etc/gluetun"
    ports:
      - "{{ infra_port_vpn_gluetun_http_proxy_host }}:{{ infra_port_vpn_gluetun_http_proxy_container }}/tcp"
      - "{{ infra_port_vpn_gluetun_shadowsocks_host }}:{{ infra_port_vpn_gluetun_shadowsocks_container }}/tcp"
      - "{{ infra_port_vpn_gluetun_shadowsocks_host }}:{{ infra_port_vpn_gluetun_shadowsocks_container }}/udp"
      - "{{ infra_port_vpn_gluetun_wireguard_host }}:{{ infra_port_vpn_gluetun_wireguard_container }}"
      - "{{ infra_port_vpn_gluetun_bt_host }}:{{ infra_port_vpn_gluetun_bt_container }}"
      - "{{ infra_port_vpn_gluetun_bt_host }}:{{ infra_port_vpn_gluetun_bt_container }}/udp"
      - "{{ infra_port_vpn_gluetun_torrent_host }}:{{ infra_port_vpn_gluetun_torrent_container }}"
      - "{{ infra_port_vpn_gluetun_prowlarr_host }}:{{ infra_port_vpn_gluetun_prowlarr_container }}"
      - "{{ infra_port_vpn_gluetun_qbittorrent_host }}:{{ infra_port_vpn_gluetun_qbittorrent_container }}"
      - "{{ infra_port_vpn_gluetun_radarr_host }}:{{ infra_port_vpn_gluetun_radarr_container }}"
      - "{{ infra_port_vpn_gluetun_lidarr_host }}:{{ infra_port_vpn_gluetun_lidarr_container }}"
      - "{{ infra_port_vpn_gluetun_sonarr_host }}:{{ infra_port_vpn_gluetun_sonarr_container }}"
    env:
      TZ: "{{ localnet_tz }}"
      VPN_SERVICE_PROVIDER: private internet access
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: "{{ wireguard_private_key }}"
      WIREGUARD_PRESHARED_KEY: "{{ wireguard_preshared_key }}"
      WIREGUARD_ADDRESSES: "{{ infra_network_vpn_gluetun_wireguard_address }}"
      VPN_PORT_FORWARDING: on
    log_driver: json-file
    log_options:
      max-size: "{{ infra_log_max_size }}"
      max-file: "{{ infra_log_max_file }}"
