graph LR
    subgraph "Transparent Mode"
        T1[Client] -->|Port 53| T2[nftables]
        T2 -->|TPROXY| T3[AdGuard]
        T3 --> A2
    end

    subgraph "Direct Mode"
        D1[Client] -->|Port 5353| D2[AdGuard]
        D2 --> A2
    end

    subgraph "VPN Mode"
        V1[VPN Client] -->|WireGuard Tunnel| V2[Host DNS]
        V2 -->|Port 5353| V3[AdGuard]
		V3 --> A2
    end

    subgraph "Remaining Stack"
        A2[dnsdist:5353] -->|Upstream DNS| A3[coredns:5353]
        A3 -->|Upstream DNS| A4[tiers:5353]
    end

    style T2 fill:#ff9999
    style D2 fill:#99ff99
    style V2 fill:#99ccff
    style T3 fill:#F4CCCC
