---
# handlers file for vpn-netbird

- name: Restart netbird (systemd)
  ansible.builtin.systemd:
    name: netbird
    state: restarted
    enabled: true
  listen: restart netbird
  become: true
  when: ansible_facts.service_mgr == 'systemd'

- name: Restart netbird (openrc)
  ansible.builtin.service:
    name: netbird
    state: restarted
    enabled: true
  listen: restart netbird
  become: true
  when: ansible_facts.service_mgr == 'openrc'
