FROM debian:12-slim

RUN apt-get update && \
    apt-get install -y curl gnupg lsb-release && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /etc/service/config /healthcheck

HEALTHCHECK --interval=30s --timeout=3s --retries=3 \
    CMD exit 0
