---
x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "5"
    tag: "{{.Name}}"
    labels: "service"

# Home services: Home Assistant + Mosquitto + ring-mqtt

volumes:
  media:

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: localnet-media-jellyfin
    logging: *default-logging
    user: "1000:1000"
    networks:
      - localnet
    ports:
      - "8096:8096"
      - "7359:7359/udp"
    environment:
      - TZ-${TIMEZONE}
      - JELLYFIN_PublishedServerUrl=http://localhost:8096
    volumes:
      - /dev/dri:/dev/dri
      - ${MEDIA_DATA_LOCATION}:/media
      - ./jellyfin/mounts/etc/jellyfin/config:/config
      - ./jellyfin/mounts/var/cache/jellyfin:/cache
    restart: unless-stopped
