---
# handlers file for proxy-traefik

- name: restart traefik
  community.docker.docker_container:
    name: "{{ proxy_traefik_container_name }}"
    state: started
    restart: true
  become: true

- name: reload traefik
  ansible.builtin.command:
    cmd: "docker kill --signal=SIGHUP {{ proxy_traefik_container_name }}"
  become: true
