---
galaxy_info:
  role_name: monitoring_node_exporter
  author: localnet
  description: Node exporter for host metrics with textfile collector.
  company: levonk
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions:
        - bookworm
    - name: Ubuntu
      versions:
        - jammy
        - noble
  galaxy_tags:
    - monitoring
    - nodeexporter
    - prometheus
    - docker

dependencies: []
