#extra-substituters = http://localnet-artifact-harmonia:5000?priority=30 http://localnet-artifact-ncps:5001?priority=40 https://cache.garnix.io?priority=60 https://cache.nixos.org?priority=80
extra-substituters = https://cache.nixos.org?priority=80

extra-trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= cache.garnix.io-1:917cK6X0+XBO7CV7MncdEVt18A8hBsN1SWqI7RliSMA=
experimental-features = nix-command flakes
# trusted-users will be set dynamically by entrypoint script

# Fallback and timeout settings for resilience
fallback = true
connect-timeout = 5
max-silent-time = 900

# We'll set up a job to do this to prevent wasted compute
auto-optimise-store = false
