extra-substituters = https://cache.nixos.org
extra-trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
experimental-features = nix-command flakes
trusted-users = root cuser

# We'll set up a job to do this to prevent wasted compute
auto-optimise-store = false
