# Changes applied to this service
_commit: 8ae9a492
_src_path: boilerplate/apps/infrastructure/docker/docker-linux

# Service Identity
_service_name: MediaManager
_service_description: TinyMediaManager - A media management tool
_service_name_slug: mediamanager
_domain: localnet

# Container & Network
_service_port: 5800
_service_health_endpoint: /
_use_traefik: true
_enable_monitoring: true

# Features
_include_ui: true
_ui_port: 5800

# Nix Configuration
_nix_system: x86_64-linux
